---
{{ if .Values.production.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-example.fullname" . }}-green
  labels:
    app.kubernetes.io/name: {{ include "springboot-example.name" . }}
    helm.sh/chart: {{ include "springboot-example.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    slot: green
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "springboot-example.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      slot: green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "springboot-example.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        slot: green
    spec:
      initContainers:
      - name: "check-mysql"
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql-release 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']  
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.green.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_SERVICE_NAME
              value: {{ .Values.mysql.servicename }}
            - name: DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.existingsecrets }}
                  key: mysql-password
            - name: MYSQL_USER
              value: {{ .Values.mysql.username }}                      
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}    
